spring:
  application:
    name: produto-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/produtosdb

eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    defaultZone: http://localhost:8761/eureka/
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#spring:
#  application:
#    name: produto-service
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/produtosdb
#  cloud:
#    discovery:
#      client:
#        service-url:
#          defaultZone: http://localhost:8761/eureka/

server:
  port: 8091