#spring:
#  application:
#    name: admin-service
#  cloud:
#    config:
#      import-check:
#        enabled: false
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: admin-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
    config:
      import-check:
        enabled: false
server:
  port: 8090